config/routes.rb
Rails.application.routes.draw do

  post 'friends' => 'friends#create'
  patch 'friends/:id' => 'friends#update'
  get 'friends/:id/destroy' => 'friends#destroy' # Horrible. But I want the destroy button in the same form in friends_table.rb

  root 'pages#home'
  get 'my_friends' => 'pages#my_friends'
  get 'saved_items' => 'pages#saved_items'
  get 'about' => 'pages#about'

  get 'items/create_or_update'
  get 'items/number_of_unviewed_items'
  get 'items' => 'items#index'
  post 'items' => 'items#create_or_update'
  delete 'items/:id' => 'items#destroy'
  get 'items/:id' => 'items#show'
  get 'username' => 'items#username'
  get 'check_login' => 'items#check_login'

  get '/sign_out' => 'sessions#destroy', :as => :sign_out
  get "/auth/:provider/callback" => 'sessions#create'

  get '/retrieve_all_records_from/:model' => "pages#retrieve_all_records_from"

end

app/views/partials/_friends_table.erb
<div class="row my-friends-div-table">
  <div class="table">
    <div class="thead">
      <div class="tr row">
        <div class="th col-sm-2">Tag</div>
        <div class="th col-sm-4">Name</div>
        <div class="th col-sm-2">Date Added</div>
        <div class="th col-sm-2"></div>
        <div class="th col-sm-2"></div>
      </div>
    </div>
  </div>
</div>

<div class="row">
<% @friends.each do |friend| %>
  <%= bootstrap_form_for(friend, url:(friends_path+"/#{friend.id}"), layout: :horizontal) do |f| %>
    <div class="xs-col-12">
    <div class="my-friends-div-table">
      <div class="table">

        <div class="tbody">
          
          <div class="tr row" id="<%= "first-row" if friend.id == @friends.first.id %>">
          
            <div class="td col-sm-2">
              <%= f.text_field :tag, hide_label: true, placeholder: "@Tag" %>
            </div>
            <div class="td col-sm-4">
              <%= friend.receiving_user_type == 'User' ? friend.receiving_user.name : friend.receiving_user.email %>
            </div>
            <div class="td col-sm-2">
              <%= friend.receiving_user.created_at.strftime("%m/%d/%Y") %>
            </div>
            <div class="td col-sm-2">
              <%= f.submit class: "btn btn-default btn-xs", method: :patch, name:"Update Button", :data => {:disable_with => 'Submitting...'} %>
            </div>
            <div class="td col-sm-2">
              <%= button_to("Delete friend", (friends_path+"/#{friend.id}/eatshit"), name:"Delete Button", class:"btn btn-default btn-xs", method: :patch, data: {confirm: "Do you really want to end your friendship? They'll likely never forgive you." }) %>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  <% end %>
<% end %>
</div>

<!-- Add a new friend to the table -->
<%= bootstrap_form_tag url:friends_path, layout: :horizontal do |f| %>
  <div class="row">
    <div class="xs-col-12">
      <div class="my-friends-div-table">
        <div class="table">
          <div class="tbody">
            <div class="tr row" id="<%= "first-row" if @friends.nil? %>">
                <div class="td col-sm-2">
                  <%= f.text_field :tag, hide_label: true, placeholder:"@Tag", title:"Must start with an @ symbol" %>
                </div>
                <div class="td col-sm-4">
                  <%= f.email_field :email, hide_label: true, placeholder: "their_email@gmail.com", class:"remove-left-padding" %>
                </div>
                <div class="td col-sm-2">
                  <%= button_tag(class: "btn btn-success btn-xs", :data => {:disable_with => 'Submitting...'}) do %>
                                  <i class='fa fa-hand-o-left'></i>  Add a New Friend!
                                <% end %>
                </div>
                <div class="td col-sm-2"></div>
                <div class="td col-sm-2"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/partials/_get_started.html.erb
<div id="get-started">
	<div class="row">
		<div class="col-md-12">
			<h3>Stop emailing sh*t to your friends!</h3>
			<h5>Stop sending that video into your friends inbox or posting it on their Facebook Timeline. Sharey makes it super easy to share content without having to leave what you're doing.</h5>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<h4>Making dinner plans?</h4>
		</div>
	</div>

			
	<div class="row vertical-align">

		<div class="col-xs-12 col-sm-4 col-md-5 text-center">
			<%= image_tag "burger-priest.png", alt:"Share this restaurant!", class:"img-thumbnail img-responsive" %>
		</div>

		<div class="col-xs-12 col-sm-4 col-md-2">
			<div class="row vertical-align">
				<div class="hidden-xs col-sm-3 col-md-2 text-center chevron">
					<i class="fa fa-chevron-right"></i>
				</div>
				<div class="hidden-sm hidden-md hidden-lg col-xs-12 text-center chevron">
					<i class="fa fa-chevron-down"></i>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-8 text-center">
					<%= image_tag "ShareyIcon_128x128_4.png", class:"img-thumbnail", id:"sharey-icon" %>
				</div>
				<div class="hidden-xs col-md-2 col-sm-3 text-center chevron">
					<i class="fa fa-chevron-right"></i>
				</div>
				<div class="hidden-sm hidden-md hidden-lg col-xs-12 text-center chevron">
					<i class="fa fa-chevron-down"></i>
				</div>
			</div>
		</div>

		<div class="col-xs-12 col-sm-4 col-md-5 text-center">
			<%= image_tag "sharey-screenshot.png", alt:"Share this restaurant!", class:"img-thumbnail img-responsive" %>
		</div>


	</div>
</div>

app/views/partials/_navbar.html.erb
<!-- NAVBAR -->
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="navbar-brand-img" href="<%= root_path %>">
        <%= image_tag "ShareyIcon_48x48_8.png", alt:"Sharey", class:"img-circle", id:"" %>
      </a>
      <a class="navbar-brand" href="<%= root_path %>">Sharey</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <%= 'class=active' if current_page?(root_path) %>><a href="<%= root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li <%= 'class=active' if current_page?(my_friends_path) %>><a href="<%= my_friends_path %>">My Friends</a></li>
        <li <%= 'class=active' if current_page?(saved_items_path) %>><a href="<%= saved_items_path %>">Saved Items</a></li>
        <li <%= 'class=active' if current_page?(about_path) %>><a href="<%= about_path %>">About</a></li>
      </ul>

      <div class="navbar-right">
        <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><a href="#"><%= "Hello " + current_user.first_name + "!" %></a></li>
          <li><%= link_to 'Sign out', sign_out_path %></li>
        </ul>
        <% else %>
            <a class="btn btn-social btn-google-plus" href='/auth/google_oauth2'>
              <i class="fa fa-google-plus"></i>
              Sign in with Google
            </a>
        <% end %>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>